# This file is part of the https://github.com/ixnode/crawl4md project.
#
# (c) 2026 Björn Hempel <bjoern@hempel.li>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#
# @author: Björn Hempel <bjoern@hempel.li>
# @version: 1.0.0 (2026-05-16)
# @since 1.0.0 (2026-05-16) First version

import unittest

from crawl4md.config import MarkdownPreprocessingConfig
from crawl4md.convert.preprocessing.rules.remove_lines import RuleRemoveLines
from tests.preprocessing.support.data_provider import RuleCase, assert_rule_case
from crawl4md.utils.progress_runner import run_progress_cases


CASES = [
    RuleCase(
        name="removes_wikipedia_subtitle",
        config=MarkdownPreprocessingConfig(
            enabled=True,
            remove_lines=[
                "[Aa]us Wikipedia, der freien Enzyklopädie",
                "[Ff]rom Wikipedia, the free encyclopedia",
            ],
        ),
        markdown=(
            "Boeing 707 aus Wikipedia, der freien Enzyklopädie\n"
            "Boeing 707 From Wikipedia, the free encyclopedia\n"
        ),
        expected="Boeing 707\nBoeing 707\n",
    ),
    RuleCase(
        name="removes_multiple_line_patterns",
        config=MarkdownPreprocessingConfig(
            enabled=True,
            remove_lines=["generated by example", r"\[draft\]"],
        ),
        markdown="Title generated by example\n[draft]\nContent\n",
        expected="Title\nContent\n",
    ),
]


class RuleRemoveLinesTests(unittest.TestCase):

    def setUp(self) -> None:
        self.maxDiff = None

    def test_remove_lines(self) -> None:
        names = [case.name for case in CASES]

        def _run(index: int) -> None:
            case = CASES[index]
            assert_rule_case(self, RuleRemoveLines, case)

        run_progress_cases(names, _run)
