import unittest

from crawl4md.config import MarkdownPreprocessingConfig
from crawl4md.convert.preprocessing.rules.remove_lines import RuleRemoveLines
from tests.preprocessing.support.data_provider import RuleCase, assert_rule_case
from tests.support.progress import run_progress_cases


CASES = [
    RuleCase(
        name="removes_wikipedia_subtitle",
        config=MarkdownPreprocessingConfig(
            enabled=True,
            remove_lines=[
                "[Aa]us Wikipedia, der freien Enzyklopädie",
                "[Ff]rom Wikipedia, the free encyclopedia",
            ],
        ),
        markdown=(
            "Boeing 707 aus Wikipedia, der freien Enzyklopädie\n"
            "Boeing 707 From Wikipedia, the free encyclopedia\n"
        ),
        expected="Boeing 707\nBoeing 707\n",
    ),
    RuleCase(
        name="removes_multiple_line_patterns",
        config=MarkdownPreprocessingConfig(
            enabled=True,
            remove_lines=["generated by example", r"\[draft\]"],
        ),
        markdown="Title generated by example\n[draft]\nContent\n",
        expected="Title\nContent\n",
    ),
]


class RuleRemoveLinesTests(unittest.TestCase):

    def setUp(self) -> None:
        self.maxDiff = None
    def test_remove_lines(self) -> None:
        names = [case.name for case in CASES]

        def _run(index: int) -> None:
            case = CASES[index]
            assert_rule_case(self, RuleRemoveLines, case)

        run_progress_cases(names, _run)
